// Cataloghi allineati agli enum di it.pagopa.pn.papertracker.model.
// Qui non c'è logica, solo dati: se cambiano gli enum, si tocca questo file.

//: statusCode -> [descrizione, tipo evento, prodotto, esito, è demat finale]
export const STATUS_CODES = {
  "RECRN006": ["Furto/Smarrimento/deterioramento", "RETRYABLE_EVENT", "AR", "PROGRESS", false],
  "RECRN013": ["Non Rendicontabile", "RETRYABLE_EVENT", "AR", "PROGRESS", false],
  "RECRN015": ["Causa Forza Maggiore", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN001C": ["Consegnato - Fascicolo Chiuso", "FINAL_EVENT", "AR", "OK", false],
  "RECRN002C": ["Mancata consegna - Fascicolo Chiuso", "FINAL_EVENT", "AR", "OK", false],
  "RECRN002F": ["Irreperibilità Assoluta - Fascicolo Chiuso", "FINAL_EVENT", "AR", "KO", false],
  "RECRN003C": ["Consegnato presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "AR", "OK", false],
  "RECRN004C": ["Mancata consegna presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "AR", "OK", false],
  "RECRN005C": ["Compiuta giacenza - Fascicolo Chiuso", "FINAL_EVENT", "AR", "OK", false],
  "RECRN011": ["In giacenza", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN001A": ["Consegnato - pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN002A": ["Mancata consegna - pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN002D": ["Irreperibilità Assoluta - pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN003A": ["Consegnato presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN004A": ["Mancata consegna presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN005A": ["Compiuta giacenza pre-esito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "RECRN001B": ["Consegnato - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN002B": ["Mancata consegna - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN002E": ["Irreperibilità Assoluta - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN003B": ["Consegnato presso Punti di Giacenza - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN004B": ["Mancata consegna presso Punti di Giacenza - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN005B": ["Compiuta giacenza - In Dematerializzazione", "INTERMEDIATE_EVENT", "AR", "PROGRESS", true],
  "RECRN010": ["Inesito", "INTERMEDIATE_EVENT", "AR", "PROGRESS", false],
  "PNRN012": ["Perfezionamento per decorrenza termini", "FINAL_EVENT", "AR", "OK", false],
  "RECRI001": ["Avviato all'estero", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", false],
  "RECRI002": ["Ingresso nel paese estero", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", false],
  "RECRI005": ["Furto, smarrimento o deterioramento", "RETRYABLE_EVENT", "RIR", "PROGRESS", false],
  "RECRI003A": ["Consegnato - pre-esito", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", false],
  "RECRI004A": ["Mancata consegna - pre-esito", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", false],
  "RECRI003B": ["Consegnato - In Dematerializzazione", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", true],
  "RECRI004B": ["Mancata consegna - In Dematerializzazione", "INTERMEDIATE_EVENT", "RIR", "PROGRESS", true],
  "RECRI003C": ["Consegnato - Fascicolo Chiuso", "FINAL_EVENT", "RIR", "OK", false],
  "RECRI004C": ["Mancata consegna - Fascicolo Chiuso", "FINAL_EVENT", "RIR", "KO", false],
  "CON998": ["Scartato NODOC", "NOT_RETRYABLE_EVENT", "ALL", "PROGRESS", false],
  "CON997": ["Scartato CAP/INTERNAZIONALE", "NOT_RETRYABLE_EVENT", "ALL", "PROGRESS", false],
  "CON996": ["Scartato PDF", "CON996_EVENT", "ALL", "PROGRESS", false],
  "CON995": ["Errore stampa", "NOT_RETRYABLE_EVENT", "ALL", "PROGRESS", false],
  "CON993": ["Errore Stampa (parziale)", "NOT_RETRYABLE_EVENT", "ALL", "PROGRESS", false],
  "CON080": ["Stampato ed Imbustato", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON020": ["Affido conservato", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON010": ["Distinta Elettronica inviata a Recapitista", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON011": ["Distinta Elettronica Sigillata", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON012": ["OK Distinta Elettronica da Recapitista", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON09A": ["Materialità Pronta", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON09B": ["Prenotazione Pickup", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "CON016": ["PICKUP Sigillata", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "CON018": ["Accettazione Recapitista", "INTERMEDIATE_EVENT", "ALL", "PROGRESS", false],
  "REC016": ["Materialità Ritirata", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "REC018": ["Accettazione Recapitista", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "REC991": ["Mancata Accettazione Recapitista", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "P000": ["Affidato al consolidatore", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "P001": ["In progress", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "P011": ["Errore di sintassi", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "P012": ["Errore semantico", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "P013": ["Errore di trasformazione", "SAVE_ONLY_EVENT", "ALL", "PROGRESS", false],
  "RECAG001A": ["Consegnato - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG002A": ["Consegnato a persona abilitata - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG003A": ["Mancata consegna - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG003D": ["Irreperibilità Assoluta - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG002B": ["Consegnato a persona abilitata - In Dematerializzazione", "INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG003B": ["Mancata consegna - In Dematerializzazione", "INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG001B": ["Consegnato - In Dematerializzazione", "INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG003E": ["Irreperibilità Assoluta - In Dematerializzazione", "INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG002C": ["Consegnato a persona abilitata - Fascicolo Chiuso", "FINAL_EVENT", "890", "OK", false],
  "RECAG003C": ["Mancata consegna - Fascicolo Chiuso", "FINAL_EVENT", "890", "OK", false],
  "RECAG001C": ["Consegnato - Fascicolo Chiuso", "FINAL_EVENT", "890", "OK", false],
  "RECAG003F": ["Irreperibilità Assoluta - Fascicolo Chiuso", "FINAL_EVENT", "890", "KO", false],
  "RECAG010": ["Inesito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG010A": ["Invio CAD", "SAVE_ONLY_EVENT", "890", "PROGRESS", false],
  "RECAG004": ["Furto/Smarrimento/deterioramento", "RETRYABLE_EVENT", "890", "PROGRESS", false],
  "RECAG015": ["Causa Forza Maggiore", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG013": ["Non Rendicontabile", "RETRYABLE_EVENT", "890", "PROGRESS", false],
  "RECAG011A": ["In giacenza", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG011B": ["In giacenza - In Dematerializzazione", "STOCK_INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG012": ["Accettazione 23L", "RECAG012_EVENT", "890", "OK", false],
  "RECAG012A": ["Accettazione 23L - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG005A": ["Consegnato presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG005B": ["Consegnato presso Punti di Giacenza - In Dematerializzazione", "STOCK_INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG005C": ["Consegnato presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "890", "PROGRESS", false],
  "RECAG006A": ["Consegna a persona abilitata presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG006B": ["Consegna a persona abilitata presso Punti di Giacenza - In Dematerializzazione", "STOCK_INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG006C": ["Consegna a persona abilitata presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "890", "PROGRESS", false],
  "RECAG007A": ["Mancata consegna presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG007B": ["Mancata consegna presso Punti di Giacenza - In Dematerializzazione", "STOCK_INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG007C": ["Mancata consegna presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "890", "PROGRESS", false],
  "RECAG008A": ["Compiuta giacenza - pre-esito", "INTERMEDIATE_EVENT", "890", "PROGRESS", false],
  "RECAG008B": ["Compiuta giacenza - In Dematerializzazione", "STOCK_INTERMEDIATE_EVENT", "890", "PROGRESS", true],
  "RECAG008C": ["Compiuta giacenza - Fascicolo Chiuso", "FINAL_EVENT", "890", "PROGRESS", false],
  "RECRS002A": ["Mancata consegna - pre-esito", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS002D": ["Irreperibilità Assoluta - pre-esito", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS004A": ["Mancata consegna presso Punti di Giacenza - pre-esito", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS005A": ["Compiuta giacenza - pre-esito", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS015": ["Causa Forza Maggiore", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS010": ["Inesito", "INTERMEDIATE_EVENT", "RS", "PROGRESS", false],
  "RECRS002B": ["Mancata consegna - In Dematerializzazione", "INTERMEDIATE_EVENT", "RS", "PROGRESS", true],
  "RECRS002E": ["Irreperibilità Assoluta - In Dematerializzazione", "INTERMEDIATE_EVENT", "RS", "PROGRESS", true],
  "RECRS004B": ["Mancata consegna presso Punti di Giacenza - In Dematerializzazione", "INTERMEDIATE_EVENT", "RS", "PROGRESS", true],
  "RECRS005B": ["Compiuta giacenza - In Dematerializzazione", "INTERMEDIATE_EVENT", "RS", "PROGRESS", true],
  "RECRS001C": ["Consegnato - Fascicolo Chiuso", "FINAL_EVENT", "RS", "OK", false],
  "RECRS002C": ["Mancata consegna - Fascicolo Chiuso", "FINAL_EVENT", "RS", "KO", false],
  "RECRS003C": ["Consegnato presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "RS", "OK", false],
  "RECRS002F": ["Irreperibilità Assoluta - Fascicolo Chiuso", "FINAL_EVENT", "RS", "KO", false],
  "RECRS004C": ["Mancata consegna presso Punti di Giacenza - Fascicolo Chiuso", "FINAL_EVENT", "RS", "KO", false],
  "RECRS005C": ["Compiuta giacenza - Fascicolo Chiuso", "FINAL_EVENT", "RS", "KO", false],
  "RECRS006": ["Furto/Smarrimento/deterioramento", "RETRYABLE_EVENT", "RS", "PROGRESS", false],
  "RECRS013": ["Non Rendicontabile", "RETRYABLE_EVENT", "RS", "PROGRESS", false],
  "RECRS011": ["In giacenza", "SAVE_ONLY_EVENT", "RS", "PROGRESS", false],
  "RECRSI004A": ["Non Consegnato - pre-esito", "INTERMEDIATE_EVENT", "RIS", "PROGRESS", false],
  "RECRSI004B": ["Non Consegnato - In Dematerializzazione", "INTERMEDIATE_EVENT", "RIS", "PROGRESS", true],
  "RECRSI003C": ["Consegnato - Fascicolo Chiuso", "FINAL_EVENT", "RIS", "OK", false],
  "RECRSI004C": ["Non Consegnato - fascicolo Chiuso", "FINAL_EVENT", "RIS", "KO", false],
  "RECRSI005": ["Furto/Smarrimento/deterioramento", "RETRYABLE_EVENT", "RIS", "PROGRESS", false],
  "RECRSI001": ["Avviato all'estero", "SAVE_ONLY_EVENT", "RIS", "PROGRESS", false],
  "RECRSI002": ["Ingresso nel paese estero", "SAVE_ONLY_EVENT", "RIS", "PROGRESS", false],
};

export const ERROR_CATEGORIES = {
  "TRACKING_ID_NOT_FOUND": "TrackingId non trovato",
  "NOT_RETRYABLE_EVENT_ERROR": "Evento not retryable ricevuto",
  "RENDICONTAZIONE_SCARTATA": "Rendicontazione scartata",
  "DATE_ERROR": "Errore nella validazione delle date della sequenza",
  "LAST_EVENT_EXTRACTION_ERROR": "Errore nell'estrazione della sequenza dall'ultimo evento",
  "REGISTERED_LETTER_CODE_ERROR": "Errore nella validazione del registeredLetterCode",
  "DELIVERY_FAILURE_CAUSE_ERROR": "Errore nella validazione del deliveryFailureCause",
  "ATTACHMENTS_ERROR": "Errore nella validazione degli allegati della sequenza",
  "MAX_RETRY_REACHED_ERROR": "Numero massimo di retry raggiunto",
  "OCR_VALIDATION": "Errore nella validazione OCR",
  "DUPLICATED_EVENT": "Errore nella validazione della presenza di eventi duplicati",
  "INVALID_STATE_FOR_STOCK_890": "Stato non valido per giacenza 890",
  "INCONSISTENT_STATE": "Tracking incompleto o incoerente con la sequenza di eventi",
  "STATUS_CODE_ERROR": "Errore nella validazione della presenza degli elementi della sequenza",
};

export const ERROR_CAUSES = {
  "GIACENZA_DATE_ERROR": "Date di inizio e fine giacenza non coerenti",
  "OCR_DUPLICATED_EVENT": "Evento di risposta duplicato",
  "OCR_DRY_RUN_MODE": "Evento di risposta ignorato: modalità dry-run attiva per l'OCR",
  "OCR_KO": "Errore nella validazione dell'OCR",
  "OCR_UNSUPPORTED_PRODUCT": "Prodotto non supportato per la validazione OCR",
  "STOCK_890_REFINEMENT_MISSING": "Spedizione 890 non perfezionata",
  "STOCK_890_REFINEMENT_ERROR": "Errore nel perfezionamento della spedizione 890",
  "VALUE_AFTER_REFINEMENT": "Evento arrivato dopo la conclusione della spedizione o durante l'attesa dell'OCR",
  "VALUES_NOT_MATCHING": "Mancano dei valori rispetto a quelli attesi",
  "INVALID_VALUES": "Valori non presenti o non validi",
  "VALUES_NOT_FOUND": "Non sono presenti tutti i valori previsti dalla macchina a stati",
  "SOURCETYPE_FILETYPE_INCOHERENT": "sourceType e fileType dell'allegato non sono coerenti",
};

//: tappe del flusso salvate su `PaperTrackings.validationFlow`
export const FLOW_STEPS = [
  ["sequencesValidationTimestamp", "Sequenza validata"],
  ["refinementDematValidationTimestamp", "Demat di perfezionamento validata"],
  ["finalEventDematValidationTimestamp", "Demat dell'evento finale validata"],
  ["finalEventBuilderTimestamp", "Evento finale costruito"],
  ["recag012StatusTimestamp", "RECAG012 registrato"],
];
